### ISSUE TITLE
Working with Derby Owners Championship World Edition

### ISSUE THREAD

**Issue by Kamikazi20** [GXTX/YACardEmu#19]
I am trying to get your code to work with Derby Owners Championship World Edition.  I am able to get the program to start up but DOCWE is stating that the Card reader is not responding.

This is all I am getting 
![image](https://github.com/GXTX/YACardEmu/assets/8756824/61bcd9c2-923e-441a-8df4-b3ea216f7b4a)

I have a usb to RS232 cable connected to my unit based on 
https://www.arcade-projects.com/threads/naomi-2-chihiro-triforce-card-reader-emulator-initial-d3-wmmt-mario-kart-f-zero-ax.814/

Let me know if there is anything I can do to help you get this working for DOC.

**Comment by GXTX** [comment]
Thanks for testing it out!

Derby, much like Virtua On requires the RS422 converter board (P/N 838-13661) between the reader and the machine. So you'd connect to that instead of directly to the Naomi, since you have a real machine it should be easy enough to figure out where to attach it.

When you get it hooked up, you'll want to set the config to be `1231BR 9600 even` (although the baud and parity at this point is just assumption based on Virtua On). If you launch via command line you can set the `-t` option which should give more info, such as if it's captured any packets from the machine.

**Comment by Kamikazi20** [comment]
Thanks for the reply and I look forward to getting this working for you.
At the time of testing, The board that you are talking about has an RS232
9-pin D. Sub female connector. It looks pretty straightforward.  I
converted the cable so that the RxD and TXD are crossed over

My current setup has has a USB to RS232 connector going directly into the
converting board rs 232 9 PIN D Sub female connector.  See picture
attached. Let me know if I got this right.

Is this setup correct or should I be connecting into the cn8 connecter of
the printer.

**Comment by GXTX** [comment]
Looks OK, do me a favor and just bridge RTX/CTS on both ends. Some controllers may not be happy that we aren't properly handling that. And yeah you'll want to be hooked up to that board, not to the printer.

**Comment by Kamikazi20** [comment]
Confirming you want a wire from RTX(pin 8) ri CTS ( pin8).
I made this cable
![bridge_RTX_CTS](https://github.com/GXTX/YACardEmu/assets/8756824/490999ec-ff06-4c4b-acc1-a110bfa433ce)

The good news is that the card reader not responding error is gone.

Now I am at a please wait.  But I am not seeing your program go back and forth with the unit. 
![PXL_20230802_230221127](https://github.com/GXTX/YACardEmu/assets/8756824/4789b5a0-67ae-43dd-82c9-86c9d5fce8a0)

**Comment by GXTX** [comment]
Right, RTS/CTS bridged on both sides, but no wires going back and forth. Did you run with `-t` option? If so and there's nothing there (it would be in the terminal screen, not web display), can you try some other baud and parity settings.

**Comment by Kamikazi20** [comment]
Please Close - I am a dummy.  I wired it wrong.

**Comment by GXTX** [comment]
Just to confirm, it works? And what were your settings? :)

**Comment by Kamikazi20** [comment]
So here was the thing I crossed the wires and aligned RXD -> RXD and TXD -> TXD. I undid the cable.

Computer -> USB to RS232 ->RS422 ->Naomi
I bought this: https://www.amazon.com/dp/B075YGKFC1?ref=ppx_yo2ov_dt_b_product_details&th=1
USB RS232 Pin out
*Notes you only need 3 wires* | CTS/RTS Bridged | You will have to modify a cable|
Pin 2 RXD
Pin 3 TXD
Pin 5 GND
**Pin 7 CTS *Wire this together with pin 8
Pin 8 RTS *Wire this together with pin 7**
It should look like this

![Pining](https://github.com/GXTX/YACardEmu/assets/8756824/2b3927d0-be47-4b42-86d3-db349e00d06f)


[config]
; basepath MUST end in a trailing slash!
;basepath = /home/wutno/cards/
basepath = C:\docwe_c\
; Linux
;serialpath = /dev/ttyUSB0
; Windows
serialpath = COM3
;serialpath = \\.\pipe\YACardEmu
; Which device should we emulate?
; C1231LR / C1231BR / S31R
targetdevice = C1231BR
;
; Optional
;
serialbaud = 9600
;Acceptable even & none
serialparity = even
apiport = 8080
autoselectedcard = card.bin


I am playing this puppy all night long.
![works](https://github.com/GXTX/YACardEmu/assets/8756824/32c772bc-f7a5-40b1-990b-118ce89b074a)

**Comment by Kamikazi20** [comment]
Thanks @GXTX

**Comment by GXTX** [comment]
Thanks again for testing :)
