### ISSUE TITLE
Pre emptively inserting card creates new empty card.bin

### ISSUE THREAD

**Issue by EmiMidnight** [GXTX/YACardEmu#22]
This is based on WMMT3DX+.
If the game boots and checks if a card exists, and or when you select "I have a card" instead of going the new card route, YACardEmu will create a 0kb card.bin and then try to load it. It will then fail and throw an invalid card size error, making the game get stuck on a card reader error. 
I think in such a case, it shouldn't make an empty new card and just return "no card inserted" imo.

**Comment by GXTX** [comment]
Agreed. Many complaints recently with it. Tbh I really find this to be a user error (and usability issue). I'll fix it soon(tm).

**Comment by GXTX** [comment]
Fixed in [3387ffa](https://github.com/GXTX/YACardEmu/commit/3387ffa2f00887248beb548ac73bf69cd909a857)
