### ISSUE TITLE
Segfault\crash if no image file exists

### ISSUE THREAD

**Issue by Nezarn** [GXTX/YACardEmu#23]
Maybe include a dummy\blank image or handle if theres no image file? (so it doesn't crash and still works as before)

**Comment by EmiMidnight** [comment]
Just created a pull request to fix this.

**Comment by GXTX** [comment]
> Maybe include a dummy\blank image

A transparent surface is created if none can be found, it was/is a bug that I didn't check for the existence of the folder.
