### ISSUE TITLE
I used it for wmmt3 card reading, but it stopped working

### ISSUE THREAD

**Issue by laiqi200889** [GXTX/YACardEmu#7]
I used it for wmmt3 card reading, but it stopped working

**Comment by GXTX** [comment]
You're gonna have to give me more info than that...

Are you playing on hardware, what does your setup look like, when did it work, what did you change, etc, etc, etc...

**Comment by laiqi200889** [comment]
I use the teknoparrot emulator. When I run wmmt3, testmode gets stuck, and then stops running

**Comment by laiqi200889** [comment]
No changes have been made to the settings

**Comment by GXTX** [comment]
Why do you believe this is an issue with the card emulator?

**Comment by laiqi200889** [comment]
Because I tried to change the ROM and teknoparrot versions, but the problem was the same

**Comment by GXTX** [comment]
And what is the problem... What does it do, what does it say... Entering testmode and crash means nothing, does YACardEmu do anything?
