### ISSUE TITLE
Windows 7 cant use this in wmmt3 /_\

### ISSUE THREAD

**Issue by MOHAAUnnamedSoldier** [GXTX/YACardEmu#8]
in release version it just crash with no error
in debug version error is missing VCRUNTIME104D.dll but i was install c++ full version in teknoparrot website,so i think its windows7 bug.. please help us to fix this/_\

**Comment by GXTX** [comment]
Thanks for testing on Windows 7!

As you know Windows 7 was deemed end of life in early 2020, and as such it's an untested platform with this. I briefly tested compiling using Visual Studio 2015 on a Windows 7 32bit VM but never attempted to play.

So... What I need from you or perhaps an interested party is to follow the build instructions in the readme, install Visual Studio 2022, compile it on your end, and use it to debug to see where it's crashing. If you do that I can patch and others can use the precompiled binaries.

**Comment by GXTX** [comment]
Fixed in 7e9d80b. Download the latest release version.

**Comment by MOHAAUnnamedSoldier** [comment]
Thanks a lot !!
